(function(){
  var guide=null,busy=false;
  function pid(){var b=document.querySelector('#productQuick [data-product].active');if(b)return b.getAttribute('data-product');return new URLSearchParams(location.search).get('product')||''}
  function cfg(){var p=pid();return guide&&guide.products?guide.products[p]:null}
  function makerRank(c,name){var out={group:3,index:999,type:'other'};if(!c)return out;(c.groups||[]).some(function(g,gi){var mi=(g.makers||[]).findIndex(function(m){return m.name===name});if(mi>=0){out={group:gi,index:mi,type:g.id};return true}return false});return out}
  function gradeRank(card){var t=((card.querySelector('.pickGrade')||{}).textContent||'').trim();if(/ハイ|HIGH/.test(t))return 0;if(/ミドル|MIDDLE/.test(t))return 1;if(/ボトム|スタンダード|STANDARD/.test(t))return 2;return 1}
  function labelFor(type){return type==='quality'?'主要':type==='balance'?'バランス':type==='price'?'価格':''}
  function apply(){if(!guide)return;var c=cfg(),holder=document.getElementById('candidatePicker');if(!holder)return;var cards=Array.prototype.slice.call(holder.querySelectorAll('.pickCard[data-pick]'));if(!cards.length)return;cards.forEach(function(card,i){var maker=((card.querySelector('.pickMaker')||{}).textContent||'').trim(),r=makerRank(c,maker),score=r.group*100+gradeRank(card)*10+r.index;card.style.order=String(score);var top=card.querySelector('.pickMaker');if(top&&r.type!=='other'&&!card.querySelector('.pickMakerClass')){var s=document.createElement('span');s.className='pickMakerClass '+r.type;s.textContent=labelFor(r.type);top.appendChild(s)}});var p=document.querySelector('.compareCandidateHead p');if(p)p.textContent='主要メーカー・上位/中位シリーズを先に表示。価格重視は「ボトム」やメーカーで絞れます。'}
  function run(){if(busy)return;busy=true;setTimeout(function(){busy=false;apply()},0)}
  function style(){if(document.getElementById('compareQualityFirstStyle'))return;var s=document.createElement('style');s.id='compareQualityFirstStyle';s.textContent='.pickMakerClass{display:inline-flex;margin-left:5px;padding:2px 5px;border-radius:999px;font-size:7px;font-weight:900;vertical-align:1px}.pickMakerClass.quality{background:#172033;color:#fff}.pickMakerClass.balance{background:#eaf2ff;color:#315c9e}.pickMakerClass.price{background:#f0f1f3;color:#626b78}@media(max-width:520px){.pickMakerClass{font-size:6.5px;padding:2px 4px}}';document.head.appendChild(s)}
  fetch('maker_choice_guide.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{products:{}}}).then(function(d){guide=d||{products:{}};style();run();var root=document.getElementById('app')||document.body;new MutationObserver(run).observe(root,{childList:true,subtree:true});window.addEventListener('popstate',run)}).catch(function(){})
})();