(function(){
  var guide=null,decision=null,busy=false;
  function pid(){var b=document.querySelector('#productQuick [data-product].active');if(b)return b.getAttribute('data-product');return new URLSearchParams(location.search).get('product')||''}
  function convertDecision(d){if(!d)return null;var groups=[];if((d.quality||[]).length)groups.push({id:'quality',makers:d.quality.map(function(m){return{name:m.maker}})});if((d.value||[]).length)groups.push({id:'price',makers:d.value.map(function(m){return{name:m.maker}})});return{groups:groups}}
  function cfg(){var p=pid(),c=guide&&guide.products?guide.products[p]:null;if(c)return c;var d=decision&&decision.products?decision.products[p]:null;return convertDecision(d)}
  function makerRank(c,name){var out={group:3,index:999,type:'other'};if(!c)return out;(c.groups||[]).some(function(g,gi){var mi=(g.makers||[]).findIndex(function(m){return m.name===name});if(mi>=0){out={group:gi,index:mi,type:g.id};return true}return false});return out}
  function makerName(card){var top=card.querySelector('.pickMaker');if(!top)return'';var badge=top.querySelector('.pickMakerClass'),text=(top.textContent||'').trim();if(badge)text=text.replace((badge.textContent||'').trim(),'').trim();return text}
  function gradeRank(card){var t=((card.querySelector('.pickGrade')||{}).textContent||'').trim();if(/ハイ|HIGH/.test(t))return 0;if(/ミドル|MIDDLE/.test(t))return 1;if(/ボトム|スタンダード|STANDARD/.test(t))return 2;return 1}
  function labelFor(type){return type==='quality'?'主要':type==='balance'?'バランス':type==='price'?'価格':''}
  function apply(){if(!guide&&!decision)return;var c=cfg(),holder=document.getElementById('candidatePicker');if(!holder)return;var cards=Array.prototype.slice.call(holder.querySelectorAll('.pickCard[data-pick]'));if(!cards.length)return;cards.forEach(function(card){var maker=makerName(card),r=makerRank(c,maker),score=r.group*100+gradeRank(card)*10+r.index;card.style.order=String(score);var top=card.querySelector('.pickMaker'),old=card.querySelector('.pickMakerClass');if(old)old.remove();if(top&&r.type!=='other'){var s=document.createElement('span');s.className='pickMakerClass '+r.type;s.textContent=labelFor(r.type);top.appendChild(s)}});if(!c){cards.forEach(function(card){card.style.order=String(gradeRank(card)*10)})}var p=document.querySelector('.compareCandidateHead p');if(p)p.textContent='主要メーカー・ハイ/ミドルを先に表示。価格重視は「ボトム」やメーカーで絞れます。'}
  function run(){if(busy)return;busy=true;setTimeout(function(){busy=false;apply()},0)}
  function style(){if(document.getElementById('compareQualityFirstStyle'))return;var s=document.createElement('style');s.id='compareQualityFirstStyle';s.textContent='.pickMakerClass{display:inline-flex;margin-left:5px;padding:2px 5px;border-radius:999px;font-size:7px;font-weight:900;vertical-align:1px}.pickMakerClass.quality{background:#172033;color:#fff}.pickMakerClass.balance{background:#eaf2ff;color:#315c9e}.pickMakerClass.price{background:#f0f1f3;color:#626b78}@media(max-width:520px){.pickMakerClass{font-size:6.5px;padding:2px 4px}}';document.head.appendChild(s)}
  function getJson(file){return fetch(file+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{products:{}}}).catch(function(){return{products:{}}})}
  Promise.all([getJson('maker_choice_guide.json'),getJson('maker_choice_guide_extra.json'),getJson('maker_decision_guides.json'),getJson('maker_decision_guides_override.json')]).then(function(all){guide=all[0]||{products:{}};guide.products=guide.products||{};Object.keys((all[1]&&all[1].products)||{}).forEach(function(id){guide.products[id]=all[1].products[id]});decision=all[2]||{products:{}};decision.products=decision.products||{};Object.keys((all[3]&&all[3].products)||{}).forEach(function(id){decision.products[id]=all[3].products[id]});style();run();var root=document.getElementById('app')||document.body;new MutationObserver(run).observe(root,{childList:true,subtree:true});window.addEventListener('popstate',run)}).catch(function(){})
})();