(function(){
  document.getElementById('header').innerHTML=KadenSite.nav('compare');
  var all={},state={product:'',filters:{},maker:'all',search:'',selected:[]};
  function get(file,fallback){return fetch(file+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():fallback}).catch(function(){return fallback})}
  function esc(v){return KadenSite.esc(v)}
  function mergeBasics(base,extra){base=base||{products:[]};(extra.products||[]).forEach(function(ep){var bp=(base.products||[]).find(function(p){return p.id===ep.id});if(!bp){base.products.push(ep);return}if(ep.label)bp.label=ep.label;if(ep.lead)bp.lead=ep.lead;(ep.makers||[]).forEach(function(em){var i=(bp.makers||[]).findIndex(function(m){return m.name===em.name});if(i>=0)bp.makers[i]=em;else bp.makers.push(em)})});return base}
  function mergeFilters(base,extra){base=base||{products:{}};base.products=base.products||{};Object.keys((extra&&extra.products)||{}).forEach(function(id){base.products[id]=extra.products[id]});return base}
  function mergeCatalog(base,extra){base=base||{products:[]};(extra.products||[]).forEach(function(ep){var bp=(base.products||[]).find(function(p){return p.id===ep.id});if(!bp){base.products.push(ep);return}var map={};(bp.candidates||[]).forEach(function(c){map[c.id]=c});(ep.candidates||[]).forEach(function(c){map[c.id]=c});bp.candidates=Object.keys(map).map(function(k){return map[k]})});return base}
  function productInfo(){return (all.basics.products||[]).find(function(p){return p.id===state.product})||{id:state.product,label:state.product,makers:[]}}
  function filterCfg(){return (all.filters.products||{})[state.product]||{axes:[],items:{},compareRows:[]}}
  function sourceCandidates(){var map={},sp=(all.sales.products||[]).find(function(p){return p.id===state.product}),cp=(all.catalog.products||[]).find(function(p){return p.id===state.product});(sp&&sp.candidates||[]).forEach(function(c){map[c.id]=c});(cp&&cp.candidates||[]).forEach(function(c){map[c.id]=c});return map}
  function inferMaker(name){var p=productInfo(),found='';(p.makers||[]).some(function(m){var n=m.name||'';if(name.indexOf(n)>=0||name.indexOf(n.replace(/（.*?）/g,''))>=0){found=n;return true}return false});if(found)return found;return String(name||'').split(/[ 　]/)[0]||'その他'}
  function gradeOf(id){var p=(all.tiers.products||{})[state.product]||{},g='';['high','middle','standard'].some(function(k){if((p[k]||[]).indexOf(id)>=0){g=k;return true}return false});return g}
  function gradeName(g){return all.tiers.labels&&all.tiers.labels[g]?all.tiers.labels[g].name:''}
  function itemList(){var cfg=filterCfg(),cands=sourceCandidates(),ids=Object.keys(cfg.items||{}),list=[];if(ids.length){ids.forEach(function(id){if(cands[id])list.push({candidate:cands[id],meta:cfg.items[id]||{}})})}else{Object.keys(cands).forEach(function(id){list.push({candidate:cands[id],meta:{}})})}return list.map(function(x){x.maker=x.meta.maker||inferMaker(x.candidate.name);x.grade=gradeOf(x.candidate.id);return x})}
  function passes(x){var cfg=filterCfg();var ok=(cfg.axes||[]).every(function(a){var sel=state.filters[a.key]||'';if(!sel)return true;var vals=x.meta[a.key]||[];return !vals.length||vals.indexOf(sel)>=0});if(!ok)return false;if(state.maker!=='all'&&x.maker!==state.maker)return false;var q=state.search.trim().toLowerCase();if(q){var t=[x.candidate.name,x.candidate.tag,x.candidate.summary,x.candidate.strength,x.meta.spec,x.maker].join(' ').toLowerCase();if(t.indexOf(q)<0)return false}return true}
  function visible(){var rank={high:0,middle:1,standard:2,'':3};return itemList().filter(passes).sort(function(a,b){return rank[a.grade]-rank[b.grade]||a.maker.localeCompare(b.maker,'ja')||a.candidate.name.localeCompare(b.candidate.name,'ja')})}
  function makersForCurrentFilters(){var old=state.maker;state.maker='all';var list=itemList().filter(passes),out=[];state.maker=old;list.forEach(function(x){if(out.indexOf(x.maker)<0)out.push(x.maker)});return out.sort(function(a,b){return a.localeCompare(b,'ja')})}
  function field(x,key){if(key==='grade')return gradeName(x.grade);if(key==='spec')return x.meta.spec||'';var ps=all.pcSpecs&&all.pcSpecs.pc&&all.pcSpecs.pc[x.candidate.id];if(state.product==='pc'&&ps&&ps[key]!=null)return ps[key];if(x.meta&&x.meta[key]!=null)return x.meta[key];return x.candidate[key]||''}
  function same(vals){var c=vals.map(function(v){return String(v||'').replace(/\s+/g,' ').trim()}).filter(Boolean);return c.length<2||c.every(function(v){return v===c[0]})}
  function compareRow(label,key,items,primary){var vals=items.map(function(x){return field(x,key)}),diff=!same(vals);return'<div class="quickCell quickLabel">'+esc(label)+'</div>'+items.map(function(x,i){var v=vals[i];return'<div class="quickCell quickValue '+(diff?'diff':'')+'">'+(v?(primary?'<strong>'+esc(v)+'</strong>':esc(v)):'—')+'</div>'}).join('')}
  function comparisonRows(items){var cfg=filterCfg(),rows=[];rows.push({key:'grade',label:'グレード',primary:true});rows.push({key:'spec',label:'基本条件',primary:true});if(state.product==='pc'){rows=rows.concat([{key:'office',label:'Office'},{key:'cpu',label:'CPU'},{key:'memory',label:'メモリ'},{key:'storage',label:'SSD / データ容量'},{key:'touch',label:'タッチパネル'},{key:'panel',label:'液晶・パネル'}])}(cfg.compareRows||[]).forEach(function(r){if(!rows.some(function(x){return x.key===r.key}))rows.push(r)});rows.push({key:'tag',label:'立ち位置'});rows.push({key:'summary',label:'向いている人'});rows.push({key:'strength',label:'主な強み'});rows.push({key:'watch',label:'注意点'});return rows.map(function(r){return compareRow(r.label,r.key,items,!!r.primary)}).join('')}
  function selectedItems(){var map={};itemList().forEach(function(x){map[x.candidate.id]=x});return state.selected.map(function(id){return map[id]}).filter(Boolean)}
  function renderCompare(){var area=document.getElementById('compareArea'),items=selectedItems();if(items.length<2){area.innerHTML='<div class="quickEmpty">比較したい商品を2〜3個タップしてください。</div>';return}area.innerHTML='<section class="quickCompare"><div class="quickCompareHead"><div><h2>同じ項目で比較</h2><p>違いがある項目を薄く強調しています。</p></div><span>横にスクロール</span></div><div class="quickScroller"><div class="quickGrid" style="--compare-count:'+items.length+'"><div class="quickCell quickLabel">商品</div>'+items.map(function(x){return'<div class="quickCell quickHeadCell"><small>'+esc(x.maker)+'</small><h3>'+esc(x.candidate.name)+'</h3><div class="quickTag">'+esc(x.candidate.tag||'')+'</div>'+(x.candidate.official?'<a target="_blank" rel="noopener" href="'+esc(x.candidate.official)+'">公式を見る</a>':'')+'</div>'}).join('')+comparisonRows(items)+'</div></div><div class="compareNote">シリーズ・仕様は販売時期や型番で変わります。購入前は公式仕様を確認してください。</div></section>'}
  function normalizeSelection(list){var visibleIds={};list.forEach(function(x){visibleIds[x.candidate.id]=true});state.selected=state.selected.filter(function(id){return visibleIds[id]});if(state.selected.length>3)state.selected=state.selected.slice(0,3)}
  function renderPicker(){var list=visible();normalizeSelection(list);var holder=document.getElementById('candidatePicker');document.getElementById('candidateCount').textContent=list.length+'件';holder.innerHTML=list.length?list.map(function(x){var sel=state.selected.indexOf(x.candidate.id)>=0,disabled=!sel&&state.selected.length>=3;return'<button class="pickCard '+(sel?'selected ':'')+(disabled?'disabled':'')+'" data-pick="'+esc(x.candidate.id)+'"><div class="pickCardTop"><div><div class="pickMaker">'+esc(x.maker)+'</div><h3>'+esc(x.candidate.name)+'</h3></div><div class="pickCheck">'+(sel?'✓':'')+'</div></div><div class="pickTag">'+esc(x.candidate.tag||'')+'</div>'+(x.meta.spec?'<div class="pickSpec">'+esc(x.meta.spec)+'</div>':'')+(x.grade?'<div class="pickGrade">'+esc(gradeName(x.grade))+'</div>':'')+'</button>'}).join(''):'<div class="quickEmpty">条件に合う比較候補がありません。</div>';Array.prototype.forEach.call(holder.querySelectorAll('[data-pick]'),function(b){b.onclick=function(){var id=b.getAttribute('data-pick'),i=state.selected.indexOf(id);if(i>=0)state.selected.splice(i,1);else if(state.selected.length<3)state.selected.push(id);renderPicker();renderCompare();renderSticky()}});renderCompare();renderSticky()}
  function renderSticky(){var box=document.getElementById('compareSticky'),items=selectedItems();box.innerHTML='<div><span>'+items.length+'商品を比較中</span><small>'+items.map(function(x){return esc(x.candidate.name)}).join(' / ')+'</small></div><button class="compareClear" id="compareClear">選択解除</button>';document.getElementById('compareClear').onclick=function(){state.selected=[];renderPicker()}}
  function renderMakers(){var makers=makersForCurrentFilters();if(state.maker!=='all'&&makers.indexOf(state.maker)<0)state.maker='all';var el=document.getElementById('makerQuick');el.innerHTML='<button class="'+(state.maker==='all'?'active':'')+'" data-maker="all">すべて</button>'+makers.map(function(m){return'<button class="'+(state.maker===m?'active':'')+'" data-maker="'+esc(m)+'">'+esc(m)+'</button>'}).join('');Array.prototype.forEach.call(el.querySelectorAll('[data-maker]'),function(b){b.onclick=function(){state.maker=b.getAttribute('data-maker');state.selected=[];renderMakers();renderPicker()}})}
  function renderAxes(){var cfg=filterCfg(),el=document.getElementById('quickAxes');el.innerHTML=(cfg.axes||[]).map(function(a){var sel=state.filters[a.key]||'';return'<div class="quickAxis"><label>'+esc(a.label)+'</label><div class="quickChips"><button class="quickChip '+(!sel?'active':'')+'" data-axis="'+esc(a.key)+'" data-value="">すべて</button>'+(a.options||[]).map(function(o){return'<button class="quickChip '+(sel===o.value?'active':'')+'" data-axis="'+esc(a.key)+'" data-value="'+esc(o.value)+'">'+esc(o.label)+'</button>'}).join('')+'</div></div>'}).join('')||'<div class="compareNote">このジャンルはそのまま商品を選んで比較できます。</div>';Array.prototype.forEach.call(el.querySelectorAll('[data-axis]'),function(b){b.onclick=function(){state.filters[b.getAttribute('data-axis')]=b.getAttribute('data-value');state.maker='all';state.selected=[];renderAxes();renderMakers();renderPicker()}})}
  function draw(){var p=productInfo();document.title=p.label+' 商品比較 | 家電販売ナレッジ';document.getElementById('compareTitle').textContent=p.label+'をパッと比較';document.getElementById('compareLead').textContent='質問に答えなくても、同じジャンルのシリーズを2〜3商品選んで主要項目を横比較できます。';state.filters={};state.maker='all';state.search='';state.selected=[];document.getElementById('compareSearch').value='';renderAxes();renderMakers();state.selected=visible().slice(0,3).map(function(x){return x.candidate.id});renderPicker()}
  function productButtons(){var products=(all.basics.products||[]).filter(function(p){return itemListFor(p.id).length});var el=document.getElementById('productQuick');el.innerHTML=products.map(function(p){return'<button class="quickChip '+(p.id===state.product?'active':'')+'" data-product="'+esc(p.id)+'">'+esc(p.label)+'</button>'}).join('');Array.prototype.forEach.call(el.querySelectorAll('[data-product]'),function(b){b.onclick=function(){state.product=b.getAttribute('data-product');history.replaceState(null,'','compare.html?product='+encodeURIComponent(state.product));productButtons();draw()}})}
  function itemListFor(pid){var old=state.product;state.product=pid;var list=itemList();state.product=old;return list}
  Promise.all([
    get('maker_basics.json',{products:[]}),get('maker_basics_override.json',{products:[]}),get('maker_basics_extra.json',{products:[]}),get('maker_basics_pc_recent.json',{products:[]}),
    get('maker_series_filters.json',{products:{}}),get('maker_series_filters_extra.json',{products:{}}),get('maker_series_filters_pc_recent.json',{products:{}}),get('maker_series_filters_camera_recent.json',{products:{}}),
    get('maker_series_catalog.json',{products:[]}),get('maker_series_catalog_pc_recent.json',{products:[]}),get('maker_series_catalog_camera_recent.json',{products:[]}),
    get('maker_series_pc_specs.json',{pc:{}}),get('sales_mode.json',{products:[]}),get('model_tiers.json',{products:{},labels:{}})
  ]).then(function(p){all.basics=mergeBasics(mergeBasics(mergeBasics(p[0],p[1]),p[2]),p[3]);all.filters=mergeFilters(mergeFilters(mergeFilters(p[4],p[5]),p[6]),p[7]);all.catalog=mergeCatalog(mergeCatalog(p[8],p[9]),p[10]);all.pcSpecs={pc:p[11].pc||{}};all.sales=p[12]||{products:[]};all.tiers=p[13]||{products:{},labels:{}};state.product=KadenSite.qs('product')||((all.basics.products||[])[0]||{}).id||'tv';productButtons();draw();document.getElementById('compareSearch').oninput=function(){state.search=this.value;state.selected=[];renderPicker()}}).catch(function(){document.getElementById('app').innerHTML='<div class="quickEmpty">比較データを読み込めませんでした。</div>'})
})();