(function(){
  var guide=null,activeGroup={},pendingMaker='';
  function esc(v){return window.KadenSite?KadenSite.esc(v):String(v||'')}
  function currentProduct(){var a=document.querySelector('.makerBasicsNav [data-p].active');if(a)return a.getAttribute('data-p');var q=new URLSearchParams(location.search).get('product');return q||''}
  function cfg(pid){return guide&&guide.products?guide.products[pid]:null}
  function groupRank(c,name){var out={rank:99,index:999,type:''};(c.groups||[]).some(function(g,i){var j=(g.makers||[]).findIndex(function(m){return m.name===name});if(j>=0){out={rank:i,index:j,type:g.id};return true}return false});return out}
  function findMakerButton(name){return Array.prototype.find.call(document.querySelectorAll('.makerPick[data-maker]'),function(b){return b.getAttribute('data-maker')===name})||null}
  function scrollToConditions(name){pendingMaker=name;var p=document.getElementById('makerChoicePending');if(p){p.textContent='「'+name+'」を優先候補にしました。下の条件を選ぶと、そのメーカーを自動で開きます。';p.classList.add('show')}var target=document.querySelector('.makerFlow .makerStep');if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}
  function openMaker(name){var b=findMakerButton(name);if(b){pendingMaker='';b.click();setTimeout(function(){var s=document.querySelector('.selectedMaker');if(s)s.scrollIntoView({behavior:'smooth',block:'start'})},80)}else scrollToConditions(name)}
  function cardHtml(m,group){return'<article class="makerChoiceCard"><div class="makerChoiceCardTop"><div class="makerChoiceCardName"><small>'+esc(group.label)+'</small><h4>'+esc(m.name)+'</h4></div><div class="makerChoiceCatch">'+esc(m.catch||'')+'</div></div><div class="makerChoiceRows"><div class="makerChoiceRow"><b>持ち味</b><span>'+esc(m.point||'')+'</span></div><div class="makerChoiceRow"><b>向く人</b><span>'+esc(m.fit||'')+'</span></div><div class="makerChoiceRow"><b>価格</b><span>'+esc(m.price||'')+'</span></div></div><button class="makerChoiceGo" data-guide-maker="'+esc(m.name)+'">このメーカーを基準に見る</button></article>'}
  function panelHtml(c,pid){var groups=c.groups||[],gid=activeGroup[pid]||((groups[0]||{}).id||''),g=groups.find(function(x){return x.id===gid})||groups[0];activeGroup[pid]=g?g.id:'';if(!g)return'';return'<div class="makerChoiceTabs">'+groups.map(function(x){return'<button class="makerChoiceTab '+(x.id===g.id?'active':'')+'" data-guide-group="'+esc(x.id)+'"><b>'+esc(x.label)+'</b><span>'+esc(x.short||'')+'</span></button>'}).join('')+'</div><div class="makerChoicePanel"><div class="makerChoicePanelHead"><div><h3>'+esc(g.label)+'</h3><p>'+esc(g.description||'')+'</p></div><strong>'+(g.id==='quality'?'最初に見るおすすめ順':'予算・用途で切り替え')+'</strong></div><div class="makerChoiceCards">'+(g.makers||[]).map(function(m){return cardHtml(m,g)}).join('')+'</div><div id="makerChoicePending" class="makerChoicePending"></div><div class="makerChoiceNote">'+esc(c.note||'')+'</div></div>'}
  function guideHtml(c,pid){return'<section class="makerChoiceGuide" data-guide-product="'+esc(pid)+'"><div class="makerChoiceIntro"><small>MAKER DECISION GUIDE</small><h2>'+esc(c.title||'メーカーから決める')+'</h2><p>'+esc(c.lead||'')+'</p><div class="makerDecisionPath"><div class="makerDecisionStep"><b>1. 主要メーカー</b><span>品質・機能の持ち味を見る</span></div><div class="makerDecisionStep"><b>2. 条件を合わせる</b><span>容量・サイズ・設置で絞る</span></div><div class="makerDecisionStep"><b>3. シリーズ比較</b><span>価格差に必要な価値があるか確認</span></div></div></div><div class="makerChoiceBody">'+panelHtml(c,pid)+'</div></section>'}
  function bindGuide(section,c,pid){Array.prototype.forEach.call(section.querySelectorAll('[data-guide-group]'),function(b){b.onclick=function(){activeGroup[pid]=b.getAttribute('data-guide-group');var body=section.querySelector('.makerChoiceBody');body.innerHTML=panelHtml(c,pid);bindGuide(section,c,pid)}});Array.prototype.forEach.call(section.querySelectorAll('[data-guide-maker]'),function(b){b.onclick=function(){openMaker(b.getAttribute('data-guide-maker'))}})}
  function renderGuide(){if(!guide)return;var pid=currentProduct(),c=cfg(pid),flow=document.querySelector('.makerFlow');if(!c||!flow)return;var old=document.querySelector('.makerChoiceGuide');if(old&&old.getAttribute('data-guide-product')===pid)return;if(old)old.remove();var wrap=document.createElement('div');wrap.innerHTML=guideHtml(c,pid);var section=wrap.firstChild;flow.parentNode.insertBefore(section,flow);bindGuide(section,c,pid)}
  function reorderMakerButtons(){if(!guide)return;var pid=currentProduct(),c=cfg(pid),area=document.getElementById('makerArea');if(!c||!area)return;var current=Array.prototype.slice.call(area.querySelectorAll('.makerPick[data-maker]'));if(!current.length)return;var desired=current.slice().sort(function(a,b){var ra=groupRank(c,a.getAttribute('data-maker')),rb=groupRank(c,b.getAttribute('data-maker'));if(ra.rank!==rb.rank)return ra.rank-rb.rank;if(ra.index!==rb.index)return ra.index-rb.index;return a.getAttribute('data-maker').localeCompare(b.getAttribute('data-maker'),'ja')});var changed=desired.some(function(n,i){return n!==current[i]});if(changed){var frag=document.createDocumentFragment();desired.forEach(function(n){frag.appendChild(n)});area.appendChild(frag)}desired.forEach(function(n){var name=n.getAttribute('data-maker'),r=groupRank(c,name);if(r.rank<99&&!n.querySelector('.makerPickGuideBadge')){var em=document.createElement('em');em.className='makerPickGuideBadge '+r.type;em.textContent=r.type==='quality'?'主要':r.type==='balance'?'バランス':'価格';n.appendChild(em)}});if(pendingMaker){var b=findMakerButton(pendingMaker);if(b){var name=pendingMaker;pendingMaker='';setTimeout(function(){b.click();var p=document.getElementById('makerChoicePending');if(p){p.textContent='「'+name+'」のシリーズを表示しました。';p.classList.add('show')}},30)}}}
  function run(){renderGuide();reorderMakerButtons()}
  fetch('maker_choice_guide.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{products:{}}}).then(function(d){guide=d||{products:{}};run();var root=document.getElementById('app')||document.body;new MutationObserver(function(){setTimeout(run,0)}).observe(root,{childList:true,subtree:true});window.addEventListener('popstate',run)}).catch(function(){})
})();