(function(){
  var guides=null,loading=false,busy=false;
  var productMap={'テレビ':'tv','冷蔵庫':'refrigerator','洗濯機':'washer','エアコン':'aircon','パソコン':'pc','カメラ':'camera','炊飯器':'rice','プリンター':'printer'};
  function currentProduct(){var q=new URLSearchParams(location.search).get('product');if(q)return q;var h=document.querySelector('.makerBasicsHero h1'),t=h?(h.textContent||''):'';var id='';Object.keys(productMap).some(function(k){if(t.indexOf(k)===0){id=productMap[k];return true}return false});return id}
  function load(cb){if(guides)return cb();if(loading)return setTimeout(function(){load(cb)},80);loading=true;fetch('maker_decision_guides.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{products:{}}}).then(function(d){guides=d||{products:{}};loading=false;cb()}).catch(function(){guides={products:{}};loading=false;cb()})}
  function esc(v){return window.KadenSite?KadenSite.esc(v):String(v||'')}
  function names(arr){return (arr||[]).map(function(x){return x.maker})}
  function sectionHtml(g){var quality=(g.quality||[]),value=(g.value||[]);function group(type,title,tag,list){if(!list.length)return'';return'<section class="decisionGroup '+type+'"><div class="decisionGroupHead"><div><small>'+esc(type==='quality'?'QUALITY / MAIN':'VALUE')+'</small><h3>'+esc(title)+'</h3></div><span>'+esc(tag)+'</span></div><div class="decisionMakerList">'+list.map(function(m){return'<div class="decisionMaker"><b>'+esc(m.maker)+'</b><strong>'+esc(m.point)+'</strong><p>'+esc(m.feature)+'</p></div>'}).join('')+'</div></section>'}return'<section class="decisionGuide" id="decisionGuide"><div class="decisionHero"><small>MODEL DECISION GUIDE</small><h2>'+esc(g.title)+'</h2><p>'+esc(g.lead)+'</p></div><div class="decisionGroups">'+group('quality','まず見る主要メーカー','品質・機能から',quality)+group('value','価格から広げるメーカー','価格重視',value)+'</div>'+(g.flow&&g.flow.length?'<div class="decisionFlow"><h3>機種決めの流れ</h3><div class="decisionFlowSteps">'+g.flow.map(function(x,i){return'<div class="decisionFlowStep" data-step="STEP '+(i+1)+'">'+esc(x)+'</div>'}).join('')+'</div></div>':'')+'</section>'}
  function insertGuide(g){var old=document.getElementById('decisionGuide');if(old)old.remove();var tabs=document.querySelector('#content .tabs')||document.querySelector('.makerBasicsHero + .tabs'),flow=document.querySelector('.makerFlow');if(flow)flow.insertAdjacentHTML('beforebegin',sectionHtml(g));else if(tabs)tabs.insertAdjacentHTML('afterend',sectionHtml(g))}
  function decorateMakers(g){var box=document.getElementById('makerArea');if(!box)return;var qs=names(g.quality),vs=names(g.value),buttons=Array.prototype.slice.call(box.querySelectorAll('.makerPick'));if(!buttons.length)return;buttons.forEach(function(b){var maker=b.getAttribute('data-maker')||'';b.classList.remove('guideQuality','guideValue');if(qs.indexOf(maker)>=0)b.classList.add('guideQuality');else if(vs.indexOf(maker)>=0)b.classList.add('guideValue')});var rank=function(b){var maker=b.getAttribute('data-maker')||'',q=qs.indexOf(maker),v=vs.indexOf(maker);if(q>=0)return q;if(v>=0)return 100+v;return 200};buttons.sort(function(a,b){return rank(a)-rank(b)}).forEach(function(b){box.appendChild(b)});Array.prototype.slice.call(box.querySelectorAll('.makerGroupDivider')).forEach(function(x){x.remove()});var firstValue=buttons.find(function(b){return b.classList.contains('guideValue')});if(firstValue){var d=document.createElement('div');d.className='makerGroupDivider';d.textContent='価格から広げる候補';box.insertBefore(d,firstValue)}}
  function run(){if(busy)return;busy=true;setTimeout(function(){busy=false;load(function(){var id=currentProduct(),g=guides.products&&guides.products[id];if(!g)return;var hero=document.querySelector('.makerBasicsHero');if(hero&&!document.getElementById('decisionGuide'))insertGuide(g);decorateMakers(g)})},0)}
  var root=document.getElementById('app')||document.body;new MutationObserver(run).observe(root,{childList:true,subtree:true});run();window.addEventListener('popstate',run)
})();