(function(){
  if(!window.fetch||!window.KadenSite)return;
  var baseFetch=window.fetch.bind(window),baseTabs=KadenSite.productTabs;
  function pathOf(input){var u=typeof input==='string'?input:(input&&input.url)||'';try{return new URL(u,location.href).pathname.split('/').pop()}catch(e){return u.split('?')[0].split('/').pop()}}
  function json(url,init){return baseFetch(url,init).then(function(r){if(!r.ok)throw new Error(url);return r.json()})}
  function mergeProducts(base,extra){base=base||{products:[]};(extra.products||[]).forEach(function(ep){var i=(base.products||[]).findIndex(function(p){return p.id===ep.id});if(i>=0)base.products[i]=ep;else base.products.push(ep)});return base}
  function mergeBasics(base,extra){base=base||{products:[]};(extra.products||[]).forEach(function(ep){var bp=(base.products||[]).find(function(p){return p.id===ep.id});if(!bp){base.products.push(ep);return}if(ep.label)bp.label=ep.label;if(ep.lead)bp.lead=ep.lead;var makers=(bp.makers||[]).slice();(ep.makers||[]).forEach(function(em){var i=makers.findIndex(function(m){return m.name===em.name});if(i>=0)makers[i]=em;else makers.push(em)});bp.makers=makers});return base}
  function mergeCatalog(base,extra){base=base||{products:[]};(extra.products||[]).forEach(function(ep){var bp=(base.products||[]).find(function(p){return p.id===ep.id});if(!bp){base.products.push(ep);return}var map={};(bp.candidates||[]).forEach(function(c){map[c.id]=c});(ep.candidates||[]).forEach(function(c){map[c.id]=c});bp.candidates=Object.keys(map).map(function(k){return map[k]})});return base}
  window.fetch=function(input,init){var name=pathOf(input);
    if(name==='consult_extra.json')return Promise.all([json(input,init),json('consult_microwave.json?v='+Date.now(),{cache:'no-store'}).catch(function(){return{products:[]}})]).then(function(a){return new Response(JSON.stringify(mergeProducts(a[0],a[1])),{status:200,headers:{'Content-Type':'application/json'}})});
    if(name==='maker_basics_extra.json')return Promise.all([json(input,init),json('maker_basics_microwave.json?v='+Date.now(),{cache:'no-store'}).catch(function(){return{products:[]}})]).then(function(a){return new Response(JSON.stringify(mergeBasics(a[0],a[1])),{status:200,headers:{'Content-Type':'application/json'}})});
    if(name==='maker_series_filters_extra.json')return Promise.all([json(input,init),json('maker_series_filters_microwave.json?v='+Date.now(),{cache:'no-store'}).catch(function(){return{products:{}}})]).then(function(a){var b=a[0]||{products:{}},e=a[1]||{products:{}};b.products=b.products||{};Object.keys(e.products||{}).forEach(function(id){b.products[id]=e.products[id]});return new Response(JSON.stringify(b),{status:200,headers:{'Content-Type':'application/json'}})});
    if(name==='maker_series_catalog.json')return Promise.all([json(input,init),json('maker_series_catalog_microwave.json?v='+Date.now(),{cache:'no-store'}).catch(function(){return{products:[]}})]).then(function(a){return new Response(JSON.stringify(mergeCatalog(a[0],a[1])),{status:200,headers:{'Content-Type':'application/json'}})});
    if(name==='model_tiers.json')return json(input,init).then(function(b){b.products=b.products||{};b.products.microwave={high:['pana_ubs10e','sharp_lsx3d','toshiba_d7000c','hitachi_w1d'],middle:['pana_bs9e','pana_bs6e','sharp_rs1d','toshiba_d5000c','toshiba_d4000c','hitachi_s8d'],standard:['pana_bs5e','sharp_u1d','sharp_wf307','toshiba_d100c','hitachi_s7d']};return new Response(JSON.stringify(b),{status:200,headers:{'Content-Type':'application/json'}})});
    return baseFetch(input,init)
  };
  KadenSite.productTabs=function(product,active){if(product&&product.id==='microwave')return '<div class="tabs"><a class="tabLink '+(active==='basics'?'active':'')+'" href="basics.html?product=microwave">基礎知識</a><a class="tabLink '+(active==='makerbasics'?'active':'')+'" href="maker_basics.html?product=microwave">メーカー・シリーズ</a></div>';return baseTabs(product,active)};
})();