(function(){
var app=document.getElementById('app');document.getElementById('header').innerHTML=KadenSite.nav('challenge');
var sales=null,p=null,customer=null,asked={},answers={};
var qs=[
 {id:'use',q:'一番重視したいことは何ですか？'},
 {id:'size',q:'容量・サイズの希望はありますか？'},
 {id:'install',q:'設置スペース・横幅に制限はありますか？'},
 {id:'feature',q:'使いたい機能はありますか？'},
 {id:'budget',q:'ご予算はどのくらいですか？'},
 {id:'frequency',q:'普段はどんな使い方が多いですか？'}
];
function esc(x){return KadenSite.esc(x)}
function rnd(a){return a[Math.floor(Math.random()*a.length)]}
function profile(pid){var gender=rnd(['男性','女性']),age=rnd(['20代','30代','40代','50代','60代']),people=rnd([1,2,2,3,4,5]);var c={gender:gender,age:age,people:people};
 if(pid==='washer'){c.use=rnd(['乾燥をほぼ毎日使いたい','洗浄力を重視したい','お手入れを楽にしたい','価格を抑えたい','シワを減らしたい']);c.size=people<=2?rnd([7,8,10]):rnd([10,12,13]);c.install=rnd(['一般的な設置スペース','奥行が厳しくコンパクト優先','大型でも設置可能']);c.feature=rnd(['ヒートポンプ乾燥','自動投入','温水・除菌','基本機能で十分']);c.budget=rnd([100000,150000,200000,250000,300000]);c.frequency=people>=3?'家族でまとめ洗いが多い':'毎日こまめに洗う'}
 else if(pid==='refrigerator'){c.use=rnd(['冷凍食品・作り置きが多い','野菜をよく使う','肉・魚の鮮度重視','価格を抑えたい']);c.size=people<=1?200:people===2?300:people===3?400:people===4?500:550;c.install=rnd(['幅60cmまで','幅65cmまで','幅68.5cm以上でも可']);c.feature=rnd(['冷凍機能','野菜室の使いやすさ','鮮度保存','基本機能で十分']);c.budget=rnd([120000,180000,220000,300000,400000]);c.frequency=rnd(['週末まとめ買い','毎日自炊','こまめに買い物'])}
 else if(pid==='tv'){c.use=rnd(['地デジ・録画','映画・配信','ゲーム','スポーツ','大画面']);c.size=rnd([43,50,55,65,75]);c.install='希望'+c.size+'型が置ける';c.feature=rnd(['録画','倍速','Mini LED','有機EL','ゲーム機能']);c.budget=rnd([80000,120000,180000,250000,350000]);c.frequency=rnd(['毎日見る','週末中心','ゲーム中心'])}
 else {c.use=rnd(['価格重視','性能重視','使いやすさ重視']);c.size='特に指定なし';c.install='一般的な環境';c.feature='基本機能';c.budget=rnd([50000,100000,150000,200000]);c.frequency='毎日使う'}return c}
function answer(id){var c=customer;if(id==='use')return c.use;if(id==='size')return typeof c.size==='number'?c.size+(p.id==='washer'?'kg':p.id==='refrigerator'?'L':p.id==='tv'?'型':''):c.size;if(id==='install')return c.install;if(id==='feature')return c.feature;if(id==='budget')return '上限 '+c.budget.toLocaleString('ja-JP')+'円くらい';return c.frequency}
function home(){app.innerHTML='<section class="challengeHero"><div class="eyebrow">SALES CHALLENGE</div><h1>接客挑戦モード</h1><p>ランダムな仮想顧客に必要なヒアリングをして、条件に合う機種を提案。聞き漏らし・条件不一致まで採点します。</p></section><section class="challengeBox"><h2>挑戦する商品</h2><div class="choiceGrid">'+sales.products.map(function(x){return'<button class="askBtn" data-p="'+esc(x.id)+'"><b>'+esc(x.label)+'</b></button>'}).join('')+'</div></section>';document.querySelectorAll('[data-p]').forEach(function(b){b.onclick=function(){p=sales.products.find(function(x){return x.id===b.dataset.p});start()}})}
function start(){customer=profile(p.id);asked={};answers={};render()}
function render(){app.innerHTML='<section class="challengeHero"><div class="eyebrow">'+esc(p.label)+' / SALES CHALLENGE</div><h1>仮想顧客を接客する</h1></section><section class="profile"><h2>来店時に分かる情報</h2><div class="profileGrid"><div class="profileItem"><small>性別</small><b>'+customer.gender+'</b></div><div class="profileItem"><small>年代</small><b>'+customer.age+'</b></div><div class="profileItem"><small>使用人数</small><b>'+customer.people+'人</b></div><div class="profileItem"><small>購買意欲</small><b>条件に合えば購入意思あり</b></div></div></section><section class="challengeBox"><h2>何をヒアリングしますか？</h2><div class="choiceGrid">'+qs.map(function(q){return'<button class="askBtn '+(asked[q.id]?'asked':'')+'" data-q="'+q.id+'">'+esc(q.q)+'</button>'}).join('')+'</div><div>'+Object.keys(answers).map(function(id){var q=qs.find(function(x){return x.id===id});return'<div class="answerLog"><b>'+esc(q.q)+'</b>'+esc(answers[id])+'</div>'}).join('')+'</div></section><section class="challengeBox"><h2>提案する機種・シリーズ</h2><p>十分に聞けたと思ったら1つ選んで提案してください。</p><div class="modelGrid">'+(p.candidates||[]).map(function(c){return'<button class="modelBtn" data-c="'+esc(c.id)+'"><b>'+esc(c.name)+'</b><br><small>'+esc(c.tag||'')+'</small></button>'}).join('')+'</div></section><div class="toolbar"><button class="actionBtn" id="new">別のお客様</button><button class="actionBtn" id="home">商品選択へ</button></div>';document.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){asked[b.dataset.q]=true;answers[b.dataset.q]=answer(b.dataset.q);render()}});document.querySelectorAll('[data-c]').forEach(function(b){b.onclick=function(){grade(p.candidates.find(function(x){return x.id===b.dataset.c}))}});document.getElementById('new').onclick=start;document.getElementById('home').onclick=home}
function terms(c){return ((c.name||'')+' '+(c.tag||'')+' '+(c.summary||'')+' '+(c.strength||'')+' '+(c.watch||'')).toLowerCase()}
function match(c){var t=terms(c),pts=0,reasons=[],u=customer.use,f=customer.feature;
 function add(ok,good,bad,w){pts+=ok?w:0;reasons.push({ok:ok,text:ok?good:bad,w:w})}
 if(p.id==='washer'){add(/乾燥/.test(u)?/ヒートポンプ|乾燥/.test(t):/洗浄|縦型|価格|バランス/.test(t),'主目的に合うシリーズです','主目的との一致が弱いです',22);add(/ヒートポンプ/.test(f)?/ヒートポンプ/.test(t):/自動投入/.test(f)?/自動投入/.test(t):/温水|除菌/.test(f)?/温水|uv|除菌|ケア/.test(t):true,'希望機能に合っています','希望機能が確認できません',20);add(customer.people>=3?/12kg|13kg|大容量/.test(t):true,'人数・容量の方向性が合っています','家族人数に対して容量面を再確認したいです',13)}
 else if(p.id==='refrigerator'){add(/冷凍/.test(u)?/冷凍/.test(t):/野菜/.test(u)?/野菜/.test(t):/鮮度|肉・魚/.test(u)?/鮮度|チルド|氷温/.test(t):true,'重視する保存性能に合っています','重視する保存性能との一致が弱いです',22);add(/60cm/.test(customer.install)?/60cm|ry|bd|gt/.test(t):true,'設置幅の方向性に合っています','設置幅条件に合わない可能性があります',20)}
 else if(p.id==='tv'){add(/ゲーム/.test(u)?/ゲーム|120|144|165/.test(t):/映画|配信/.test(u)?/映画|有機el|oled|画質/.test(t):/録画/.test(u)?/録画|タイムシフト/.test(t):true,'視聴用途に合っています','主な視聴用途との一致が弱いです',25)} else add(true,'基本条件に合っています','',20);
 var heard=Object.keys(asked).length;pts+=Math.round(35*heard/qs.length);reasons.push({ok:heard>=5,text:'ヒアリング '+heard+'/'+qs.length+'項目',w:35});var max=100;pts=Math.min(max,pts+10);return{score:pts,reasons:reasons}}
function grade(c){var r=match(c),cls=r.score>=80?'good':r.score>=60?'mid':'bad',buy=r.score>=80&&asked.install&&asked.budget;app.innerHTML='<section class="challengeHero"><div class="eyebrow">RESULT</div><h1>接客結果</h1></section><section class="scoreBox"><div class="scoreNum '+cls+'">'+r.score+'点</div><h2>'+esc(c.name)+'</h2><div class="buy '+(buy?'good':'bad')+'">'+(buy?'購入意思あり':'今回は保留')+'</div><p>'+(buy?'条件との一致度が高く、必要な確認もできています。':'条件不一致またはヒアリング不足があります。')+'</p></section><section class="challengeBox"><h2>採点理由</h2>'+r.reasons.map(function(x){return'<div class="reason"><b class="'+(x.ok?'good':'bad')+'">'+(x.ok?'✓ ':'△ ')+esc(x.text)+'</b></div>'}).join('')+'<h3>顧客の本当の条件</h3>'+qs.map(function(q){return'<div class="reason"><b>'+esc(q.q)+'</b><br>'+esc(answer(q.id))+(asked[q.id]?'':' <span class="bad">（未ヒアリング）</span>')+'</div>'}).join('')+'</section><div class="toolbar"><button class="actionBtn primary" id="retry">同じお客様でもう一度</button><button class="actionBtn" id="next">次のお客様</button><button class="actionBtn" id="home">商品選択へ</button></div>';document.getElementById('retry').onclick=function(){asked={};answers={};render()};document.getElementById('next').onclick=start;document.getElementById('home').onclick=home}
fetch('sales_mode.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){sales=d;home()}).catch(function(){app.innerHTML='<div class="empty">接客データを読み込めませんでした。</div>'})
})();