window.KadenSite=(function(){
  var files=['knowledge.json','knowledge_network.json','knowledge_mobile.json','knowledge_support_game.json','knowledge_audio_apple.json','knowledge_camera_printer.json','knowledge_wifi.json','knowledge_pc.json','knowledge_vaio.json','knowledge_pc_makers.json','knowledge_tv_makers.json','knowledge_refrigerator_makers.json','knowledge_refrigerator_series.json','knowledge_washer_makers.json','knowledge_aircon_makers.json','knowledge_aircon_series.json','knowledge_aircon_install.json','knowledge_zeroemi.json','knowledge_storage_wearables.json','knowledge_recycle.json'];
  function fetchJson(url){return fetch(url+'?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(url);return r.json()})}
  function loadKnowledge(){return Promise.all(files.map(function(f){return fetchJson(f).catch(function(){return[]})})).then(function(parts){return parts.reduce(function(a,b){return a.concat(Array.isArray(b)?b:[])},[])})}
  function loadConfig(){return Promise.all([fetchJson('consult_config.json'),fetchJson('consult_extra.json').catch(function(){return{products:[]}})]).then(function(all){var base=all[0]||{products:[]},extra=all[1]||{products:[]};(extra.products||[]).forEach(function(ep){var bp=(base.products||[]).find(function(p){return p.id===ep.id});if(!bp){base.products.push(ep);return}if(ep.lead)bp.lead=ep.lead;if(ep.questions)bp.questions=ep.questions;if(ep.route)bp.route=ep.route;if(ep.makers){var current=(bp.makers||[]).slice();ep.makers.forEach(function(em){var i=current.findIndex(function(m){return m.name===em.name||((em.name==='FMV（富士通）')&&(m.name==='富士通'||m.name==='FMV'))||((em.name==='NEC LAVIE')&&(m.name==='NEC'))||((em.name==='三菱電機 霧ヶ峰')&&(m.name==='三菱電機'))||((em.name==='日立 白くまくん')&&(m.name==='日立'))||((em.name==='ゼネラル（nocria）')&&(m.name==='ゼネラル'))});if(i>=0)current[i]=em;else current.push(em)});bp.makers=current}});return base})}
  function loadOfficialLinks(){return Promise.all([fetchJson('official_links.json').catch(function(){return[]}),fetchJson('official_links_extra.json').catch(function(){return[]})]).then(function(parts){return parts.reduce(function(a,b){return a.concat(Array.isArray(b)?b:[])},[])})}
  function qs(name){return new URLSearchParams(location.search).get(name)||''}
  function esc(v){return String(v||'').replace(/[&<>"']/g,function(x){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]})}
  function getProduct(config,id){return (config.products||[]).find(function(p){return p.id===id})||(config.products||[])[0]}
  function itemMatchesProduct(item,product){var cat=String(item.cat||'');return (product.keywords||[]).some(function(k){return cat===k||cat.indexOf(k)>=0})}
  function makerNames(config){var out=['三菱電機','三菱','霧ヶ峰','Panasonic','パナソニック','日立','白くまくん','東芝','シャープ','AQUA','アクア','Haier','ハイアール','REGZA','レグザ','SONY','ソニー','TCL','Hisense','ハイセンス','Canon','キヤノン','EPSON','エプソン','Brother','brother','ブラザー','DJI','GoPro','Apple','VAIO','HP','Lenovo','NEC','LAVIE','FUJITSU','富士通','FMV','GENERAL','ゼネラル','nocria','ノクリア','Technics','Audio-Technica','Anker','Soundcore','Beats','Victor','JVC','HUAWEI','Mibro','BUFFALO','バッファロー','ELECOM','エレコム','ダイキン'];(config.products||[]).forEach(function(p){(p.makers||[]).forEach(function(m){if(out.indexOf(m.name)<0)out.push(m.name)})});return out}
  function isMakerItem(item,config){var t=[item.title,item.tag,item.body].join(' ');return makerNames(config).some(function(n){return t.indexOf(n)>=0})}
  function officialFor(item,links){var t=[item.cat,item.tag,item.title,item.body].join(' ');return (links||[]).filter(function(l){return (l.match||[]).every(function(k){return t.toLowerCase().indexOf(String(k).toLowerCase())>=0})}).slice(0,3)}
  function stage(item,config){var t=[item.title,item.tag,item.body].join(' ');if(/最初|まず|確認|ヒアリング|選び方|設置|容量|用途|買い替え/.test(t))return 1;if(/違い|仕組み|方式|種類|液晶|OLED|Mini LED|ドラム|縦型|インク|規格|センサー|F値|シャッター|Wi-Fi 5|Wi-Fi 6|Wi-Fi 7/.test(t))return 2;if(isMakerItem(item,config)||/メーカー|シリーズ/.test(t))return 3;if(/保証|録画|HDD|SSD|ケーブル|工事|注意|回収|修理|サポート|周辺/.test(t))return 4;return 2}
  function sortByConsult(items,config){return items.slice().sort(function(a,b){var d=stage(a,config)-stage(b,config);if(d)return d;return String(a.title).localeCompare(String(b.title),'ja')})}
  function nav(active){var pages=[['index.html','商品コンサル','home'],['sales_mode.html','接客モード','sales'],['basics.html','基礎知識','basics'],['maker_basics.html','メーカー基礎','makerbasics'],['makers.html','メーカー比較','makers'],['memo.html','端末メモ','memo']];return '<header class="siteHeader"><div class="shell"><div class="headRow"><a class="brand" href="index.html">家電販売ナレッジ</a><div class="nav">'+pages.map(function(p){return'<a class="'+(active===p[2]?'active':'')+'" href="'+p[0]+'">'+p[1]+'</a>'}).join('')+'</div></div></div></header>'}
  function productTabs(product,active){var id=encodeURIComponent(product.id),extra='';if(['tv','refrigerator','washer'].indexOf(product.id)>=0)extra+='<a class="tabLink '+(active==='makerbasics'?'active':'')+'" href="maker_basics.html?product='+id+'">メーカー基礎</a>';if(product.id==='aircon')extra+='<a class="tabLink '+(active==='install'?'active':'')+'" href="aircon_install.html">工事確認</a>';return '<div class="tabs"><a class="tabLink '+(active==='consult'?'active':'')+'" href="product.html?product='+id+'">コンサル</a><a class="tabLink '+(active==='sales'?'active':'')+'" href="sales_mode.html?product='+id+'">接客モード</a><a class="tabLink '+(active==='basics'?'active':'')+'" href="basics.html?product='+id+'">基礎知識</a>'+extra+'<a class="tabLink '+(active==='makers'?'active':'')+'" href="makers.html?product='+id+'">メーカー比較</a></div>'}
  return{loadKnowledge:loadKnowledge,loadConfig:loadConfig,loadOfficialLinks:loadOfficialLinks,qs:qs,esc:esc,getProduct:getProduct,itemMatchesProduct:itemMatchesProduct,isMakerItem:isMakerItem,officialFor:officialFor,stage:stage,sortByConsult:sortByConsult,nav:nav,productTabs:productTabs};
})();

(function(){
  if(!window.fetch)return;
  var nativeFetch=window.fetch.bind(window);
  window.fetch=function(input,init){
    var url=typeof input==='string'?input:(input&&input.url)||'';
    if(/(^|\/)sales_mode\.json(\?|$)/.test(url)){
      var overrideFiles=['sales_mode_aircon.json','sales_mode_refrigerator.json','sales_mode_tv.json','sales_mode_washer.json','sales_mode_pc.json'];
      return Promise.all([nativeFetch(input,init).then(function(r){if(!r.ok)throw new Error('sales_mode');return r.json()})].concat(overrideFiles.map(function(file){return nativeFetch(file+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():null}).catch(function(){return null})}))).then(function(all){var base=all[0]||{products:[]};all.slice(1).forEach(function(override){if(!override)return;var i=(base.products||[]).findIndex(function(p){return p.id===override.id});if(i>=0)base.products[i]=override;else base.products.push(override)});return new Response(JSON.stringify(base),{status:200,headers:{'Content-Type':'application/json'}})})
    }
    return nativeFetch(input,init)
  };
})();

(function(){
  if(!/sales_mode\.html$/.test(location.pathname))return;
  var key='kaden_pc_color_pref_v1',busy=false;
  function isPcScreen(){var e=document.querySelector('.modeHero .eyebrow');return !!(e&&/パソコン/.test(e.textContent||''))}
  function color(){try{return sessionStorage.getItem(key)||''}catch(e){return''}}
  function addField(){var grid=document.querySelector('.conditionGrid');if(!grid||!isPcScreen()||document.getElementById('pcColorPref'))return;var box=document.createElement('div');box.className='conditionField';box.innerHTML='<label>希望カラー</label><input id="pcColorPref" list="pcColorList" placeholder="例：ブラック / シルバー / ネイビー"><datalist id="pcColorList"><option value="ブラック"><option value="ホワイト"><option value="シルバー"><option value="ネイビー"><option value="ブルー"><option value="ゴールド"><option value="ピンク"></datalist>';
    grid.appendChild(box);var input=document.getElementById('pcColorPref');input.value=color();input.addEventListener('input',function(){try{sessionStorage.setItem(key,input.value.trim())}catch(e){}})
  }
  function patchSearch(){var c=color(),result=document.querySelector('.webSearchSection');if(!c||!result||!isPcScreen())return;if(!document.querySelector('[data-pc-color-tag]')){var req=document.querySelector('.requirements');if(req){var tag=document.createElement('div');tag.className='requirement';tag.setAttribute('data-pc-color-tag','1');tag.innerHTML='<small>希望カラー</small><b>'+window.KadenSite.esc(c)+'</b>';req.appendChild(tag)}}var qbox=document.getElementById('searchQuery');if(qbox&&qbox.textContent.indexOf(c)<0)qbox.textContent=qbox.textContent+' '+c;Array.prototype.forEach.call(document.querySelectorAll('.searchNow,.officialSearch'),function(a){if(a.getAttribute('data-color-patched')==='1')return;try{var u=new URL(a.href),q=u.searchParams.get('q')||'';if(q.indexOf(c)<0){u.searchParams.set('q',q+' '+c);a.href=u.toString()}a.setAttribute('data-color-patched','1')}catch(e){}})
  }
  function run(){if(busy)return;busy=true;setTimeout(function(){busy=false;addField();patchSearch()},0)}
  var root=document.getElementById('app')||document.body;new MutationObserver(run).observe(root,{childList:true,subtree:true});run()
})();