(function(){var app=document.getElementById('app');document.getElementById('header').innerHTML=KadenSite.nav('challenge');var c,asked={},sel={},talk={damage:false,neww:false,damageReason:'',newwReason:''};
var price=59980;
var questions=[{id:'software',q:'ソフトはダウンロード版とパッケージ版、どちらが多いですか？'},{id:'broken',q:'今までゲーム機を壊したことはありますか？'},{id:'family',q:'ご家族・お子様も一緒に使いますか？'},{id:'carry',q:'外へ持ち運ぶことは多いですか？'},{id:'storage',q:'ダウンロードソフトをたくさん入れる予定ですか？'}];
var addons=[{id:'case',name:'ケース'},{id:'film',name:'保護フィルム'},{id:'package',name:'パッケージソフト'},{id:'memory',name:'メモリーカード'}];
var reasonDefs={
 damage:[{id:'broken',label:'以前ゲーム機を壊した経験'},{id:'family',label:'家族・子どもも使う'},{id:'carry',label:'外へ持ち運ぶ'}],
 neww:[{id:'broken',label:'過去の故障経験・故障への不安'},{id:'family',label:'家族で長く使う予定'},{id:'carry',label:'持ち運びを含め長く使いたい'}]
};
function rnd(a){return a[Math.floor(Math.random()*a.length)]}function esc(x){return KadenSite.esc(x)}function start(){c={software:rnd(['ダウンロード版中心','パッケージ版中心','まだ決めていない']),broken:rnd(['以前ゲーム機を壊したことがある','壊したことはない']),family:rnd(['子どもを含む家族で使う','本人中心で使う']),carry:rnd(['よく持ち運ぶ','家で使うことが多い']),storage:rnd(['ダウンロードソフトを多く入れたい','数本程度の予定'])};asked={};sel={};talk={damage:false,neww:false,damageReason:'',newwReason:''};render()}
function ans(id){return c[id]}function need(id){if(id==='case')return asked.carry&&c.carry==='よく持ち運ぶ';if(id==='film')return asked.family&&c.family.indexOf('子ども')>=0;if(id==='package')return asked.software&&c.software==='パッケージ版中心';if(id==='memory')return asked.software&&asked.storage&&c.software==='ダウンロード版中心'&&c.storage.indexOf('多く')>=0;return false}
function reasonAvailable(type,r){return !!asked[r.id]}
function reasonFit(type,id){if(!id)return 0;if(id==='broken')return c.broken.indexOf('壊したことがある')>=0?3:1;if(id==='family')return c.family.indexOf('子ども')>=0?(type==='damage'?3:2):1;if(id==='carry')return c.carry.indexOf('よく持ち運ぶ')>=0?(type==='damage'?3:2):1;return 0}
function reasonButtons(type){return reasonDefs[type].map(function(r){var av=reasonAvailable(type,r),on=talk[type+'Reason']===r.id;return'<button class="btn '+(on?'on':'')+'" data-reason="'+type+':'+r.id+'" '+(av?'':'disabled')+'><b>'+esc(r.label)+'</b><br><small>'+(av?'ヒアリング済み':'未ヒアリング')+'</small></button>'}).join('')}
function render(){app.innerHTML='<section class="hero"><div class="eyebrow">SWITCH 2 SALES CHALLENGE</div><h1>Switch 2 コンサル挑戦モード</h1><p>仮想顧客をヒアリングして、本体保証と付帯品を提案してください。</p></section><section class="box"><h2>来店時に分かる情報</h2><div class="grid"><div class="log"><small>本体価格</small><br><b>'+price.toLocaleString()+'円</b></div><div class="log"><small>購買意欲</small><br><b>Switch 2購入予定</b></div></div></section><section class="box"><h2>ヒアリング</h2><div class="grid">'+questions.map(function(q){return'<button class="btn '+(asked[q.id]?'on':'')+'" data-q="'+q.id+'">'+esc(q.q)+'</button>'}).join('')+'</div>'+questions.filter(function(q){return asked[q.id]}).map(function(q){return'<div class="log"><b>'+esc(q.q)+'</b><br>'+esc(ans(q.id))+'</div>'}).join('')+'</section><section class="box"><h2>保証をどう説明する？</h2><p>保証を選んだあと、<b>どのヒアリング内容を理由におすすめするか</b>を選択してください。相手の回答と理由が合っているほど加入見込みが上がります。</p><div class="grid"><button class="btn '+(talk.damage?'on':'')+'" data-talk="damage"><b>物損保証 20%</b><br><span class="price">'+Math.round(price*.2).toLocaleString()+'円</span><br><small>落下・持ち運び・子どもの使用などの事故リスク向け</small></button><button class="btn '+(talk.neww?'on':'')+'" data-talk="neww"><b>新品保証 40%</b><br><span class="price">'+Math.round(price*.4).toLocaleString()+'円</span><br><small>故障経験や長期利用への不安に合わせて案内</small></button></div>'+(talk.damage?'<h3>物損保証をおすすめする理由</h3><div class="grid">'+reasonButtons('damage')+'</div>':'')+(talk.neww?'<h3>新品保証をおすすめする理由</h3><div class="grid">'+reasonButtons('neww')+'</div>':'')+'</section><section class="box"><h2>付帯品を提案</h2><div class="grid">'+addons.map(function(a){return'<button class="btn '+(sel[a.id]?'on':'')+'" data-a="'+a.id+'"><b>'+a.name+'</b><br><small>'+(need(a.id)?'ヒアリングからおすすめ候補':'必要と思えば提案')+'</small></button>'}).join('')+'</div></section><div class="toolbar"><button class="btn primary" id="finish">提案を確定して採点</button><button class="btn" id="new">別のお客様</button></div>';document.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){asked[b.dataset.q]=true;render()}});document.querySelectorAll('[data-a]').forEach(function(b){b.onclick=function(){sel[b.dataset.a]=!sel[b.dataset.a];render()}});document.querySelectorAll('[data-talk]').forEach(function(b){b.onclick=function(){var t=b.dataset.talk;talk[t]=!talk[t];if(!talk[t])talk[t+'Reason']='';render()}});document.querySelectorAll('[data-reason]').forEach(function(b){b.onclick=function(){var x=b.dataset.reason.split(':'),k=x[0]+'Reason';talk[k]=talk[k]===x[1]?'':x[1];render()}});document.getElementById('finish').onclick=grade;document.getElementById('new').onclick=start}
function warrantyScore(type,reasons){var chosen=talk[type+'Reason'];if(!talk[type])return{join:0,score:0};if(!chosen){reasons.push((type==='damage'?'物損保証':'新品保証')+'：おすすめ理由を選んでいない');return{join:10,score:-8}}var fit=reasonFit(type,chosen),label=(reasonDefs[type].find(function(r){return r.id===chosen})||{}).label||chosen;if(fit===3){reasons.push((type==='damage'?'物損保証':'新品保証')+'：'+label+'を根拠にした提案が非常に合っています');return{join:type==='damage'?60:65,score:8}}if(fit===2){reasons.push((type==='damage'?'物損保証':'新品保証')+'：'+label+'を根拠にした提案は合っています');return{join:45,score:4}}reasons.push((type==='damage'?'物損保証':'新品保証')+'：'+label+'を理由にしたが、お客様の回答との一致が弱い');return{join:20,score:-5}}
function grade(){var score=100,reasons=[],critical=['software','broken','family'];critical.forEach(function(id){if(!asked[id]){score-=15;reasons.push('重要ヒアリング漏れ：'+questions.find(function(q){return q.id===id}).q)}});addons.forEach(function(a){if(need(a.id)&&!sel[a.id]){score-=12;reasons.push('ヒアリング内容に合う付帯品を未提案：'+a.name)}if(!asked.software&&(a.id==='package'||a.id==='memory')&&sel[a.id]){score-=8;reasons.push('ソフト購入方法を聞かずに'+a.name+'を提案')}});var join=0,d=warrantyScore('damage',reasons),n=warrantyScore('neww',reasons);join+=d.join+n.join;score+=d.score+n.score;if(!talk.damage&&!talk.neww){score-=15;reasons.push('保証の必要性を案内していない')}join=Math.min(95,join);score=Math.max(0,Math.min(100,score));var cls=score>=80?'good':score>=60?'mid':'bad';app.innerHTML='<section class="hero"><div class="eyebrow">RESULT</div><h1>Switch 2 接客結果</h1></section><section class="result"><div class="score '+cls+'">'+score+'点</div><h2>保証加入見込み '+join+'%</h2><p>加入率は「保証を案内したか」だけでなく、<b>ヒアリングした内容のどこを理由にしたか</b>と、その理由が実際のお客様像に合っているかで決まります。</p></section><section class="box"><h2>結果理由</h2>'+(reasons.length?reasons.map(function(x){return'<div class="reason">'+esc(x)+'</div>'}).join(''):'<div class="reason good">ヒアリングと提案が適切です。</div>')+'<h3>今回のお客様</h3>'+questions.map(function(q){return'<div class="reason"><b>'+q.q+'</b><br>'+ans(q.id)+(asked[q.id]?'':' <span class="bad">（未ヒアリング）</span>')+'</div>'}).join('')+'</section><div class="toolbar"><button class="btn primary" id="again">次のお客様</button></div>';document.getElementById('again').onclick=start}start()})();