(function(){
var host=document.getElementById('app');if(!host)return;
var btn=document.createElement('button');btn.type='button';btn.className='quickChip';btn.textContent='全ジャンル自由比較';btn.style.cssText='font-weight:700;border:2px solid #2563eb';
var target=document.getElementById('productQuick');if(!target)return;document.querySelector('.compareHero').appendChild(btn);
var pane=document.createElement('section');pane.id='universalCompare';pane.style.display='none';pane.innerHTML='<div class="compareBox"><h2>全ジャンル自由比較</h2><p>ビデオカメラとアクションカメラ、PCとタブレットなど、ジャンルを問わず横に追加できます。空欄は「—」と表示します。</p><input id="universalSearch" class="compareSearch" placeholder="機種名・メーカー・ジャンルで検索"><div id="universalChoices" class="candidatePicker" style="margin-top:12px"></div><div id="universalPicked" style="margin:12px 0"></div><div id="universalTable" style="overflow-x:auto"></div><button id="universalClear" class="quickChip" type="button">選択をすべて解除</button></div>';
document.getElementById('compareArea').parentNode.insertBefore(pane,document.getElementById('compareArea'));
var original=[document.querySelector('.compareControls'),document.querySelector('.compareCandidateHead'),document.getElementById('candidatePicker'),document.getElementById('compareSticky'),document.getElementById('compareArea')];var active=false,records=[],picked=[];
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fetchJ(f){return fetch(f+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{}}).catch(function(){return{}})}
function mergeCatalog(dst,o){(o.products||[]).forEach(function(p){(p.candidates||[]).forEach(function(c){dst[c.id]=Object.assign({},dst[c.id]||{},c,{category:p.id})})})}
function mergeMeta(dst,o){Object.keys(o.products||{}).forEach(function(pid){var items=o.products[pid].items||{};Object.keys(items).forEach(function(id){dst[id]=Object.assign({},dst[id]||{},items[id])})})}
var files=['maker_series_catalog.json','maker_series_catalog_pc_recent.json','maker_series_catalog_camera_recent.json','maker_series_catalog_vaio_t.json','maker_series_catalog_microwave.json','maker_series_catalog_tv32.json'];var filters=['maker_series_filters.json','maker_series_filters_extra.json','maker_series_filters_pc_recent.json','maker_series_filters_camera_recent.json','maker_series_filters_vaio_t.json'];
Promise.all(files.concat(filters).map(fetchJ)).then(function(a){var cat={},meta={};a.slice(0,files.length).forEach(function(x){mergeCatalog(cat,x)});a.slice(files.length).forEach(function(x){mergeMeta(meta,x)});records=Object.keys(cat).map(function(id){return Object.assign({},cat[id],{meta:meta[id]||{}})});render()});
function val(x,k){var m=x.meta||{};return m[k]||x[k]||''}
function render(){if(!active)return;var q=document.getElementById('universalSearch').value.toLowerCase().trim();var matches=records.filter(function(x){return !q||[x.name,x.tag,x.category,x.meta.maker,x.summary].join(' ').toLowerCase().includes(q)}).slice(0,100);document.getElementById('universalChoices').innerHTML=matches.map(function(x){var yes=picked.includes(x.id);return'<button type="button" class="pickCard '+(yes?'selected':'')+'" data-universal="'+esc(x.id)+'"><div class="pickMaker">'+esc(x.meta.maker||x.name.split(' ')[0])+' · '+esc(x.category)+'</div><h3>'+esc(x.name)+'</h3><div class="pickTag">'+(yes?'✓ 比較中':'＋ 追加')+'</div></button>'}).join('')||'<p>該当する商品がありません。</p>';document.querySelectorAll('[data-universal]').forEach(function(b){b.onclick=function(){var id=this.getAttribute('data-universal'),i=picked.indexOf(id);if(i<0)picked.push(id);else picked.splice(i,1);render()}});var sel=picked.map(function(id){return records.find(function(x){return x.id===id})}).filter(Boolean);document.getElementById('universalPicked').innerHTML='<b>選択中：'+sel.length+'商品</b> '+sel.map(function(x){return'<button type="button" class="quickChip" data-remove="'+esc(x.id)+'">'+esc(x.name)+' ×</button>'}).join('');document.querySelectorAll('[data-remove]').forEach(function(b){b.onclick=function(){picked=picked.filter(function(id){return id!==b.getAttribute('data-remove')});render()}});var rows=[['ジャンル','category'],['タイプ','typeLabel'],['センサー','sensor'],['動画解像度','resolution'],['レンズ・ズーム','lens'],['手ブレ補正','stabilization'],['AF','af'],['重量','weight'],['内蔵メモリー','internal'],['記録媒体','memory'],['対応カード容量','maxCapacity'],['カード速度','speed'],['CPU','cpu'],['メモリ','memory'],['SSD・容量','storage'],['Office','office'],['主な強み','strength'],['向いている人','summary'],['注意点','watch']];var html='<table style="border-collapse:collapse;min-width:'+Math.max(700,200+sel.length*230)+'px;width:100%;font-size:14px"><thead><tr><th style="position:sticky;left:0;background:#eef2f7;min-width:135px;padding:12px">比較項目</th>'+sel.map(function(x){return'<th style="min-width:210px;padding:12px;background:#eef2f7">'+esc(x.name)+(x.official?'<div><a href="'+esc(x.official)+'" target="_blank" rel="noopener">公式仕様 ↗</a></div>':'')+'</th>'}).join('')+'</tr></thead><tbody>';rows.forEach(function(row,i){html+='<tr><th style="position:sticky;left:0;background:'+(i%2?'#f2f5f9':'#fff')+';padding:10px;border-bottom:1px solid #dce3ea;text-align:left">'+esc(row[0])+'</th>'+sel.map(function(x){var v=val(x,row[1]);if(row[0]==='メモリ'&&x.category==='pc')v=x.meta.memory||'';if(row[0]==='記録媒体'&&x.category==='pc')v='';return'<td style="padding:10px;border-bottom:1px solid #dce3ea;background:'+(i%2?'#f8fafc':'#fff')+';vertical-align:top">'+esc(v||'—')+'</td>'}).join('')+'</tr>'});html+='</tbody></table>';document.getElementById('universalTable').innerHTML=sel.length?html:'<div class="quickEmpty">商品を追加すると横並びの比較表が表示されます。</div>'}
btn.onclick=function(){active=!active;pane.style.display=active?'block':'none';original.forEach(function(x){if(x)x.style.display=active?'none':''});btn.classList.toggle('active',active);document.getElementById('compareTitle').textContent=active?'全ジャンル自由比較':'商品をパッと比較';if(active)render()};
document.getElementById('universalSearch').oninput=render;document.getElementById('universalClear').onclick=function(){picked=[];render()};
})();